### ISSUE TITLE
Pre-Install-Check:  Update tool to correctly parse modified json from storage class

### ISSUE THREAD

**Issue by lasiva** [sassoftware/viya4-ark#103]
The following traceback is captured running tool against latest cluster.
$ python viya-ark.py pre-install-report  -i "nginx" -n deployment  -H dkdkdk -p 27373
Gathering facts...................................DONE

Traceback (most recent call last):
  File "viya-ark.py", line 139, in <module>
    main(sys.argv[1:])
  File "viya-ark.py", line 77, in main
    command.run(argv[1:])
  File "C:\Public\viya401\github\develop_4_6\viya4-ark\pre_install_report\pre_install_report.py", line 98, in run
    main(argv)
  File "C:\Public\viya401\github\develop_4_6\viya4-ark\pre_install_report\pre_install_report.py", line 271, in main
    sas_pre_check_report.check_details(kubectl, ingress_port, ingress_host, ingress_controller, output_dir)
  File "C:\Public\viya401\github\develop_4_6\viya4-ark\pre_install_report\library\pre_install_check.py", line 123, in check_details
    storage_data = self._get_storage_classes(storage_json)
  File "C:\Public\viya401\github\develop_4_6\viya4-ark\pre_install_report\library\pre_install_check.py", line 331, in _get_storage_classes
    node_data['selfLink'] = node['metadata']['selfLink']

**Comment by spljaa** [comment]
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md : Stop propagating SelfLink (deprecated in 1.16) in kube-apiserver (#94397, @wojtek-t) [SIG API Machinery and Testing

**Comment by kevinlinglesas** [comment]
This issue is resolved in release [1.3.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.3.0).
