### ISSUE TITLE
Issue executing Deployment Report on develop branch using --include-pod-log-snips

### ISSUE THREAD

**Issue by kevinlinglesas** [sassoftware/viya4-ark#80]
This traceback was reported executing on develop branch.
```Generating deployment report......................DONE
Traceback (most recent call last):
  File "viya-ark.py", line 139, in <module>
    main(sys.argv[1:])
  File "viya-ark.py", line 77, in main
    command.run(argv[1:])
  File "...\viya4-ark\deployment_report\deployment_report.py", line 48, in run
    main(argv)
  File "...\viya4-ark\deployment_report\deployment_report.py", line 134, in main
    include_pod_log_snips=args.include_pod_log_snips)
  File "...\viya4-ark\deployment_report\model\viya_deployment_report.py", line 236, in gather_details
    log_snip: List = kubectl.logs(pod_name)
TypeError: logs() missing 1 required positional argument: 'container_name'```

This was run against deployment to AWS.

**Comment by kevinlinglesas** [comment]
Release [1.2.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.2.0) satisfies this issue.
