### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by frayos** [sassoftware/viya4-ark#84]
Hello,
Trying "download-pod-logs", git cloned it "now"  and getting the below issue 

[cloud-user@rext03-0009 viya4-ark]$ python3 viya-ark.py download-pod-logs --namespace lab --tail 1000

Downloading pod logs..............................DONE
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/cloud-user/viya4-ark/download_pod_logs/model.py", line 233, in _write_log
    file_content = SASStructuredLoggingParser.parse_log(log)
  File "/home/cloud-user/viya4-ark/viya_ark_library/structured_logging/parser.py", line 40, in parse_log
    unstructured_log.append(SASStructuredLoggingParser.parse_log_entry(log_entry))
  File "/home/cloud-user/viya4-ark/viya_ark_library/structured_logging/parser.py", line 65, in parse_log_entry
    if required_key not in structured_log_entry:
TypeError: argument of type 'int' is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "viya-ark.py", line 139, in <module>
    main(sys.argv[1:])
  File "viya-ark.py", line 77, in main
    command.run(argv[1:])
  File "/home/cloud-user/viya4-ark/download_pod_logs/download_pod_logs.py", line 47, in run
    main(argv)
  File "/home/cloud-user/viya4-ark/download_pod_logs/download_pod_logs.py", line 146, in main
    selected_components=args.selected_components, tail=args.tail, noparse=args.noparse)
  File "/home/cloud-user/viya4-ark/download_pod_logs/model.py", line 150, in download_logs
    err_info: List[Tuple[Optional[Text], Text]] = process.get_process().get(timeout=self._wait)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: argument of type 'int' is not iterable

Am I missing something ? 
Thanks !
Younes

**Comment by frayos** [comment]
(on master branch)

**Comment by frayos** [comment]
(this was on BYO K8S made by GEL)

**Comment by frayos** [comment]
tried downloading the 1.1.1 release in case but same issue

**Comment by erharb** [comment]
@sasjowood I think this is the same thing being fixed in #81. Please confirm and dup this one if so.

**Comment by sasjowood** [comment]
@frayos and @erharb, that is correct, this issue is currently being tracked in issue #81. Please watch issue #81 for updates on the status of this fix. I'm closing this as a duplicate.
