### ISSUE TITLE
Deployment Report: Traceback using Kubernetes Server & Client (kubectl) version v1.19+

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#85]
(Per @StuartAAustin)

An error is raised when generating a Deployment Report with Kubernetes Client (`kubectl`) version **v1.19+** causing the following traceback:

```python
Traceback (most recent call last):
  File "viya-ark.py", line 139, in <module>
    main(sys.argv[1:])
  File "viya-ark.py", line 77, in main
    command.run(argv[1:])
  File "/install/viya-ark/viya4-ark/deployment_report/deployment_report.py", line 48, in run
    main(argv)
  File "/install/viya-ark/viya4-ark/deployment_report/deployment_report.py", line 134, in main
    include_pod_log_snips=args.include_pod_log_snips)
  File "/install/viya-ark/viya4-ark/deployment_report/model/viya_deployment_report.py", line 169, in gather_details
    networking_kind)
  File "/install/viya-ark/viya4-ark/deployment_report/model/utils/viya_deployment_report_utils.py", line 59, in gather_resource_details
    api_resources.get_name(resource_kind))
  File "/install/viya-ark/viya4-ark/viya_ark_library/k8s/sas_kubectl.py", line 294, in get_resources
    resources_list: List = json.loads(resource_json.decode()).get(KubernetesResource.Keys.ITEMS)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The issue stems from a new warning that is printed when `kubectl get ingresses` is run at **v1.19+**:

```cmd
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

This warning causes a parsing error when the output from the command is parsed as JSON.

### Work-around

Revert the `kubectl` installation to a version _less than_ **v1.19+**.

**Comment by kevinlinglesas** [comment]
Release [1.2.1](https://github.com/sassoftware/viya4-ark/releases/tag/1.2.1) satisfies this issue.
