### ISSUE TITLE
Deployment Report: Error generating report against new Ingress definitions

### ISSUE THREAD

**Issue by sasjowood** [sassoftware/viya4-ark#86]
(Per @jkmin96)

An error is raised when generating a Deployment Report against a deployment containing new Ingress definitions (version `networking.k8s.io/v1`), causing the following traceback:

```python
Generating deployment report......................DONE
Traceback (most recent call last):
File "viya-ark.py", line 139, in <module>
  main(sys.argv[1:])
File "viya-ark.py", line 77, in main
  command.run(argv[1:])
File "/local/install/viya4-ark/deployment_report/deployment_report.py", line 48, in run
  main(argv)
File "/local/install/viya4-ark/deployment_report/deployment_report.py", line 134, in main
  include_pod_log_snips=args.include_pod_log_snips)
File "/local/install/viya4-ark/deployment_report/model/viya_deployment_report.py", line 202, in gather_details
  gathered_resources[k8s_kinds.INGRESS])
File "/local/install/viya4-ark/deployment_report/model/utils/viya_deployment_report_utils.py", line 167, in define_service_to_ingress_relationships
  http_path[KubernetesResource.Keys.BACKEND][KubernetesResource.Keys.SERVICE_NAME]
KeyError: 'serviceName'
```

The issue stems from a change in the **service name** key between the new Ingress version (`networking.k8s.io/v1`) and the old, soon-to-be-deprecated version (`extensions/v1beta1`).

The new definition defines the value under:

```yaml
spec.rules[].http.paths[].backend.service.name
```

the old definition defines the value under

```yaml
spec.rules[].http.paths[].backend.serviceName
```

This change causes the `KeyError` that is raised.

### Proposed Fix

Use the version of the Ingress object that is returned to determine the path for access to the **service name** key.

**Comment by kevinlinglesas** [comment]
Release [1.2.0](https://github.com/sassoftware/viya4-ark/releases/tag/1.2.0) satisfies this issue.
